version: '3'

services:
  web:
    image: buoyantio/emojivoto-web:v1
    environment:
      - WEB_PORT=8080
      - EMOJISVC_HOST=emoji-svc:8080
      - VOTINGSVC_HOST=voting-svc:8080
      - INDEX_BUNDLE=dist/index_bundle.js
    ports:
      - "8080:8080"
    depends_on:
      - voting-svc
      - emoji-svc

  emoji-svc:
    image: buoyantio/emojivoto-emoji-svc:v1
    environment:
      - GRPC_PORT=8080
    ports:
      - "8081:8080"

  voting-svc:
    image: buoyantio/emojivoto-voting-svc:v1
    environment:
      - GRPC_PORT=8080
    ports:
      - "8082:8080"
